# Generated by Django 5.1.7 on 2025-05-14 17:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commission", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionByPriceRange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("min_price", models.FloatField()),
                ("max_price", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
