# Generated by Django 5.1.7 on 2025-06-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commission", "0002_commissionbypricerange"),
    ]

    operations = [
        migrations.AddField(
            model_name="commissionbypricerange",
            name="commission",
            field=models.FloatField(default=0),
        ),
    ]
