# Generated by Django 5.1.7 on 2025-05-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("number", "0010_number_approval_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="number",
            name="is_upc_transferred",
            field=models.BooleanField(default=False),
        ),
    ]
