# Generated by Django 5.1.7 on 2025-06-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("number", "0011_number_is_upc_transferred"),
    ]

    operations = [
        migrations.AlterField(
            model_name="number",
            name="parent_operator",
            field=models.CharField(
                choices=[
                    ("JIO", "jio"),
                    ("AIRTEL", "airtel"),
                    ("VI", "vi"),
                    ("BSNL", "bsnl"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
