# Generated by Django 5.1.7 on 2025-04-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vendors",
            "0003_alter_vendor_aadhar_card_alter_vendor_agreement_form_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
