# Generated by Django 5.1.7 on 2025-04-18 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("number", "0003_number_circle_number_current_operator_and_more"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="number_sales",
                to="number.number",
            ),
        ),
    ]
