# Generated by Django 5.1.7 on 2025-05-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_remove_sales_number_sales_numbers"),
        ("vendors", "0007_vendor_account_holder_name_vendor_account_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sales",
            name="vendor",
        ),
        migrations.AddField(
            model_name="sales",
            name="vendors",
            field=models.ManyToManyField(related_name="sales", to="vendors.vendor"),
        ),
    ]
