# Generated by Django 5.1.7 on 2025-06-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_remove_sales_vendor_sales_vendors"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="sales_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
