# Generated by Django 5.1.7 on 2025-06-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_sales_sales_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sales",
            name="status",
        ),
        migrations.AddField(
            model_name="sales",
            name="order_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="sales",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("closed_won", "Closed-Won"),
                    ("duplicate", "Duplicate"),
                    ("cancelled", "Cancelled"),
                    ("wrong_data", "Wrong Data"),
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sales",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("paid", "Paid"),
                    ("pending", "Pending"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sales",
            name="total_excl_gst",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="sales",
            name="total_incl_gst",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="sales",
            name="upc_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sales",
            name="vendor_rate",
            field=models.FloatField(default=0.0),
        ),
    ]
