# Generated by Django 5.1.7 on 2025-06-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_remove_sales_status_sales_order_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="agent_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sales",
            name="agent_order_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
